%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/marcus/Workspace/Matlab/Matlab-NWMR/Nanook/Nanook_Vels.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/01/28 11:40:30
clear;close all;clc
%% Initialize variables.
filename = '/home/marcus/Workspace/Matlab/Matlab-NWMR/Nanook/Nanook_Vels.csv';
delimiter = ',';
startRow = 4;

%% Format for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Setpoint = dataArray{:, 1};
M_D = dataArray{:, 2};
M_E = dataArray{:, 3};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

%% Regressão Linear

% Y = X . B
% Y -> leitura ; X -> modelo ; B -> Parâmetros para estimar
Y_D = M_D;
Y_E = M_E;
n = length(Setpoint);
% Modelo definido aqui (X)
X = Setpoint; %b*x
% X = [ones(n,1) Setpoint]; %b0 + b1*x
% X = [ones(n,1) Setpoint Setpoint.*Setpoint]; %b0 + b1*x + b2*x^2

% e = Y - XB

B_D = inv(X'*X)*X'*Y_D;
B_E = inv(X'*X)*X'*Y_E;

% Erro médio quadrático
disp('Modelo -> ')
disp(X)

disp('Erro médio quadrático')
E_D_v = Y_D - X*B_D;
E_D = E_D_v'*E_D_v

% Erro médio quadrático
E_E_v = Y_E - X*B_E;
E_E = E_E_v'*E_E_v
B_D
B_E

setpoint = X(:,end);
plot(setpoint,X*B_D)
hold on
plot(setpoint,Y_D)
grid on;
title('Regressão M_D')
legend('Estimação','Saída')
figure
plot(setpoint,X*B_E)
hold on
plot(setpoint,Y_E)
grid on;
title('Regressão M_E')
legend('Estimação','Saída')


















